import "./globals.css";

import localFont from "@next/font/local";
const archia = localFont({
  src: "../public/fonts/archia-regular-webfont.woff2",
  variable: "--font-archia",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${archia.variable} font-sans`}>
      <body>{children}</body>
    </html>
  );
}
